<?php include '../../../../includes/header.html'; ?>

<?php include "navigation.html"; ?>	

<?php $title = 'Bestien'; ?>

<?php include 'path.php'; ?>		
			
<div>
	<p>Echsen
	Die Echsen sind das älteste Volk Ults sie entwickelten sich aus kleinen Urreptilien vor über 30.000 Jahren, ohne das Zutun irgendeiner Gottheit, da diese zu der damaligen zeit auch viel zu sehr mit sich selbst beschäftigt waren. Sie bewohnen den Südlichen Dschungel von Gorn der mit seinen hohen Luftfeuchtigkeit und Umgebungstemperatur perfekt geeignet ist für solche Kaltblüter wie die Echsenmenschen. Hier ist ihre Kultur die ungeschlagene Nummer eins, da kein anderes Volk mit der Vielseitigkeit und der natürlichen Kampfkraft einer Echse mithalten kann. Sollten sie den Dschungel einmal verlassen verlieren sie ihre Agilität und werden mit sinkender Temperatur immer langsamer bis zur Kältestarre, was ein Glück für die sonstigen Kreaturen Ults ist, da sie sonst bereits allesamt von den Echsenmenschen vernichtet worden währen. 
	Durch die lange Endwicklungszeit haben sich die unterschiedlichsten Formen von Echsenmenschen entwickelt. Es gibt die Mächtigen Trax die mehrere Tausend Jahre alt werden und völlig aufgebläht aussehen vor lauter Magie die sie in ihrem langen leben aufgesaugt haben, sie sind die mächtigsten Magier Ults und höchsten Priester der Echsen. Obwohl Echsenmenschen keine Götter verehren spielt Religion und die Trax als oberste Priester, eine große Rolle für die Echsen. Angebetet werden vor allem Urgeister denen sehr häufig große Opfer nach Schlachten dargebracht werden. Die Form der Opferung liegt immer am Urgeist für den geopfert werde soll, Herz herausschneiden, In einen Vulkan schmeißen... , was immer gleich bleibt ist, dass die unterlegene Partei eines Konfliktes geopfert wird. 
	Wesentlich kleiner und kurzlebiger sind die kleinen Skirks sie sind klein und schwach wie Goblins, haben aber ein ausgeprägteres Übehrlebensbewusstsein als diese, weswegen sie meistens in Gruppen aus dem Hinterhalt mit ihren Bögen attackieren in größeren schlachten werden sie meistens als Plänkler eingesetzt. Die eigentlichen Echsenmenschen sind etwa 2m groß und haben eine Grün-braune Schuppenhaut. Sie werden einmal von den Trax angeführt, haben daneben aber auch noch einen König aus ihrer Mitte. Ein neuer König wird immer dann gekrönt, wenn der Andere gerade in einem Zweikampf gefallen ist, dies gewährleistet dass immer der stärkste Krieger der Anführer ist. Trotz des Enormen alters der Echsenkultur sind sie eigentlich noch sehr primitiv. Das einzige Metall was sie verarbeiten ist Gold, welches zu Schmuckzwecken gebraucht und kalt geformt wird. Als Waffen benutzen sie Keulen und Speere, die mit spitzten und scharfkantigen Osidiansplittern verstärkt werde und zum Schutz verwenden sie ausschließlich Holz, Hornhaut und Knochen, vornehmlich artverwandter Tiere, welche sie auch zum Kampfeinsatz und zum Reiten benutzten. Die Schamanen, die Magie wirken neben den Trax, können auf einen reichen Fundus aus tropischen Pflanzen zurückgreifen. 
	
	Orks
	Orks sind ein humanoides Volk, dass für seine groben Gesichtszüge und ihre Brutalität im Kampf bekannt sind. Sie sind etwas größer als Menschen, ihr Haar ist gewöhnlich dunkel und zerzaust und ihre Hautfarbe ist hell- bis moosgrün. Orks werden nicht für sehr Intelligent gehalten, vor allem durch den sehr einfachen Satzbau den sie verwenden, im Gefecht aber gefürchtet.
	Früher waren Orks beinahe über ganz Ult verteilt, seid der Gründung des Imperiums, durch den ersten Hochkaiser und Imperator vor ca.800 Jahren wurden sie aber aus der Tiefebene von Ios und den Mittlanden in ihre Kerngebiete die Stosteppe zurückgedrängt.
	Die Orks leben noch als Sammler und Jäger in Lederzelten, haben aber auch ein paar befestigte Siedlungen gegründet, die Wichtigste ist wohl Waag, da hier in den Goblinminen Eisen abgebaut wird. Schmieden können die Orks zwar nicht, aber aus dem Eisen werden Gusseiserne Waffen und Rüstungen gefertigt. Diese sind zwar im Verhältnis wesentlich schwerer, aber einem Ork macht Gewicht wohl kaum etwas aus. Andere Gegenstände oder Waffen werden aus Horn, Knochen, Leder, Holz und Stein gefertigt.
	Das Höchste Ansehen genießt immer der Stärkste Krieger und erfolgreichste Jäger, die meiste Macht aber haben die Schamanen inne. Sie sind zwar „nur“ Berater, aber sie nehmen doch den entscheidenden Einfluss auf den Häuptling.
	
	„ Wenn’s nich Grün is dann hau solang zu bis es nicht mehr zappelt,
	und dann nochma, um sicha zusein!“
	
	Mehrmals haben sich die Orks schon versucht, unter starken Häuptlingen geeint, das Imperium zurückzuschlagen. Das letzte Mal im Jahre 12.537 a.e. mit einem Waahhrg unter der Führung Garahgs, dem sich alle Stämme und vor allem viele Goblins anschlossen, die Hoffnung auf reiche Beute hatten. Der Waahhrg war auch recht erfolgreich, so konnte der Tyrogwall bezwungen und weite Teile des Hinterlandes verwüstet werden. Aufgehalten wurden die Orks schließlich vom 13. Rgt unter Gregor III  genannt, der Herrscher, der es durch ein glückliches Flankenmanöver, an dessen Spitze er ritt, schaffte den Waahhrgführer Garahg zu töten. Leider brach der Kampfgeist der Orks nicht (außer  eine handvoll liefen alle Goblins weg), und bis auf wenige Soldaten und Ritter die den strategischen Rückzug Hals über Kopf antraten wurde das 13.Rgt von Trumsh dem Riesen aufgerieben. In den darauffolgenden Stänkereien unter den Orks selber, dezimierten sie sich derart gegenseitig, dass die neu formierte Imperiale Armee keine weiteren Schwierigkeiten mit ihnen hatten, was ein sehr schöner Beweis für die mangelnde Disziplin der Orks darstellt.
	Die Orkfrauen sind stämmig gebaut und genauso stark wie ihre männlichen Pedanten, ziehen aber selten mit in den Krieg, sondern kümmern sich um die Kinder, die Alten oder Verletzte. Das heißt allerdings nicht, dass sie wehrlos sind. So Mancher Feldherr, der die Gunst der Stunde ausnutzen wollte, sah sich plötzlich mit einer Horde wütender Orkfrauen konfrontiert, mit denen auch nicht gut Kirschen essen ist.
	Kinder wird man wenn überhaupt nur sehr selten sehen, denn nach einer Tragezeit von 24 Monaten im Bauch der Mutter kommt der Frischling relativ weit entwickelt zur Welt und kann direkt Laufen. Mit Zwei Jahren, in denen es Täglich bis zum doppelten seines eigenen Körpergewichts essen kann, ist der Ork ausgewachsen und fertig entwickelt, was dafür verantwortlich ist, dass Orks nur eingeschränkte Intelligenz besitzen. Das Durchschnittsalter eines Orks ist 50 wobei einzelne Orks meistens Schamanen oder Frauen über 70 werden können. Stirbt ein Ork, wird er im Feuer bestattet, damit er nicht von Slage, den alle Orks Hassen, geholt werden kann, sondern zu ehren Ologs starb. 
	Olog, die Urwut, ist zwar ursprünglich kein Gott sondern Urgeist aber trotzdem ehren sie ihn indem sie für ihn opfern und zu ihm beten. Daneben gibt es noch weitere niedere Urgeister wie die Urkraft Uruz, die ebenfalls eine Rolle in der Religion spielen. 
	
	„Er trägt seine Narben wie andere ihre Ruhmesauszeichnungen – um 
	seine Gegner zu warnen, dass er nicht einfach zu besiegen ist.“
	</p>
</div>

<?php include '../../../../includes/footer.html'; ?>