<?php include '../../../../includes/header.html'; ?>

<?php include "navigation.html"; ?>	

<?php $title = 'Elfen'; ?>

<?php include 'path.php'; ?>		
			
<div>
	<p>Die ursprünglichen Elfen, die Hochelfen wurden von keinem Gott Ults erschaffen, sondern kamen, wie es eine uralte Legende berichtet, vom Himmel herabgefahren. Sie verfügten über wahnsinnige magische Kräfte, schlugen mit Energieklingen zu und hatten Panzer die härter waren als solche, die der Sage nach aus Drachenschuppen gefertigt werden. Sie kamen gerade rechtzeitig zu den II. Götterkriegen und nur mit ihrer Unterstützung konnte die Herrschaft Kers abgeschüttelt werden. Danach verließen die Hochelfen die Gefilde Ults wieder fast vollständig. Nur ein paar wenige blieben um im Dienste Ganjas als Wächter der großen Wälder zu dienen.

	Waldelfen
	Diese Elfen sind wirklich gar sonderbar. Sie scheinen unnahbar, zeitweilen sogar gefühlskalt, sie zeigen keinerlei Gefühlsregungen weder Freude noch Schmerz. Ganz anders durfte ich sie erleben, als mir die große Ehre zuteil wurde einmal eine Elfenstadt betreten zu dürfen. Dort schienen sie ausgelassen, sorglos und freudig untereinander.
	Waldelfen haben leicht dunkle haselnussbraune Haut, dunkelbraunes bis schwarzes langes Haar, welches manchmal mit ein geflochtenen Bändern und Federn verziert sind, und grüne Augen. Sie werden rund 1,75 m groß und sind drahtig gebaut, wodurch sie ausgezeichnet durchs Geäst und Gebüsch huschen können. Waldelfen sind sehr feinfühlige Wesen, dadurch können sie sich auch bedingt mit Tieren und Pflanzen unterhalten. Allerdings führt es dazu, dass sie schnell Mitleid bekommen, welches sie fremden gegenüber aber niemals zeigen würden und es würde sie schon gar nicht daran hindern Gegner und Eindringlinge nieder zu schlachten, wenn diese es nicht anders verdient haben.
	Verarbeitet werden vor allem feste Stoffe, Felle, Leder und Holz. Metall wird kaum benutzt dafür werden reiche Verzierungen in Holz geschnitzt. Die Kleidung ist meistens sehr eng anliegend und mit wenigen Verzierungen um nicht unnötig im Gestrüpp zu behindern.
	Die Hauptwaffe der Waldelfen ist ihr Langbogen der aus einem Stück Ebenholz gefertigt und durch doppelnde Reflexzierung der wahrscheinlich mächtigste Bogentyp Ults ist. Neben ihrem Bogen verwenden die Waldelfen aber auch normale Schlagstöcke, Speere und Schilde aus Schwarzeichenholz, welches beinahe so stark wie Eisen ist. Manchmal tragen Elfen auch normale Metallische Klingen wie Dolche und Schwerter, welche sie ertauscht oder gefunden haben, aber im Normalfall kennen sie wirkungsvollere Waffen.
	Die Waldelfen leben in den Weiten des Nebelwaldes in einfachen Holzbauten und Baumhäusern im Einklang mit den meisten anderen Waldbewohnern, wie den Nebelwalddryaden oder den Baumhirten. Die Behausungen sind aber nicht aus Holz gezimmert, sondern bestehen aus noch lebendem Holz, wobei sie  auf eine ganz bestimmte Art den Baum so wachsen lässt, dass sie als Unterkunft für die Waldelfen geeignet sind. Es gibt neben mehreren kleinen Außenposten nur zwei größere Städte der Waldelfen. Almere, welches mitten im Nebelwald liegt am Fluss Neblunga und Evadal, welches am Blauen Ozean liegt.
	Die Waldelfen sind zwar von Ganja als Hüter der Wälder eingesetzt worden, das heißt aber nicht, dass sie pazifistische Baumknutscher sind. Längst ist der Wald ihre Heimat geworden, welche verteidigt werden will gegen wen auch immer.
	
	„Der Nebelwald bedeckt mehrere tausend Quadratkilometer Fläche
	 und trotzdem betritt ihn keiner, ohne das die Waldelfen es
	 nicht mitbekommen würden.“
	
	Geführt werden die Elfen von einem Rat aus 12 besonders weisen Elfen, Ihre Söhne werden Ryhin was so etwas wie Prinz bedeutet, genannt und sind häufig Führer in Kampf, genießen aber sonst keine Vorteile.
	Waldelfen sind zwar keine Vegetarier und essen auch gerne mal Fleisch, es steht aber nicht so häufig wie Früchte oder Wurzelknollen auf dem Speiseplan. Um weitere Strecken schnell zu überwinden reiten sie manchmal auf gezähmten Höhlentigern, die ihnen auch im Kampf dienen. Formationskämpfe haben Waldelfen nicht in ihrem Repertoire an Schlachtplänen, da sie ja meistens im Wald kämpfen, bevorzugen sie eher Tarntaktiken. Außerdem kämpfen Waldelfen in drei Dimensionen, wogegen normale Soldaten meistens nur zwei bedenken.
	Alt gilt man ab ungefähr 230 Jahren und obwohl Elfen bei den meisten anderen Völkern als unsterblich gelten müssen auch sie irgendwann einmal gehen. Als unsterblich gelten sie nur, weil sie optisch gesehen nicht mehr älter werden nach ihrem 30. Lebensjahr. Waldelfen wissen wann ihre Zeit gekommen ist, und darum ziehen sich die meisten älteren Waldelfen mit ca.270 Jahren zurück zum sterben. Sie werden in den Bäumen bestattet damit ihre Seele möglichst rasch entweichen kann. 
	
	Der Glaube und die Feste der Waldelfen 
	Als Religion haben die Waldelfen nur Ganja als ihre Gönnerin und verschiedene Urgeister, wie Uriel den Geist der Gewässer,  Narbaf die Lebenskraft oder Nistram die Luft, zu deren ehren auch die unterschiedlichsten Feste gefeiert werden wie z.B. das Lichtfest, das Fest des Lebens oder das Windfest, wobei in den Bäumen Klanghölzer und Federschmuck aufgehängt werden, so dass der Wind darin spielen kann. Neben den Festen um die Göttin und die Geister zu ehren werden noch die Persönlichen feste der Geburt und des Abschieds gefeiert.
	Kleriker gibt es keine unter den Elfen, dafür sind die Druiden zuständig, die für die Verehrung Ganjas und der Urgeister sorgen. Die Druiden beziehen ihre macht sowohl von Ganja, als auch von den Urgeistern.
	
	Beziehungen der Elfen
	Waldelfen pflegen kaum außenpolitische Beziehungen und halten auch nicht allzu viel vom Handel. Nur die Halblinge dürfen den Wald betreten und die Elfensiedlungen besuchen kommen. Beziehungen mit den Menschen kommen zwar vor, vor allem am Rand des Nebelwaldes, Elfen neigen aber dazu sich nur in ihrer Heimat und unter Ihresgleichen  richtig wohl zu fühlen. 
	Halbelfen sind die einzige Art von Bastarden die es auf Ult gibt. Sie entstehen nur wenn die Mutter elfisch ist. Ist es der Vater, dann entwickeln sie sich zu ganz normalen Menschen, wo lediglich eventuell eine grüne Augenfärbung auftreten kann. Halbelfen wachsen daher meistens mit ihren Müttern bei den Waldelfen auf. Von diesen wird er nicht verstoßen, sondern im Gegenteil wird er bemitleidet und wie ein behindertes Kind behandelt, da Halbelfen weder das Alter, noch die Fähigkeiten von richtigen Elfen erreichen können. Das führt dazu, dass Halbelfen meist auch keine Ausbildung haben, weder an der Waffe oder sonst noch welche. 
	Feindseligkeiten gibt es viele. Wie die gegen die Schattenelfen und ihren Orkischen Helfern im Norden oder ungebeten eindringende Menschen oder Zwerge. 
	
	Schattenelfen
	Schattenelfen sind die bösen Geschwister der Waldelfen. Und besiedeln seit etwa 12.000 Jahren die Sturmspitze wovon aus sie sich tief in die Unterwelt hineingefressen haben. Das Leben in der Unterwelt ist dafür verantwortlich, dass sie extrem gut in der Dunkelheit sehen können. Schattenelfen sind etwas schmächtiger als Waldelfen im Körperbau gleichen ihren Oberflächenvettern aber ansonsten in den meisten Charakteristika, außer ihrer dunkelblauen, meistens mit leichtem lila Einschlag, versehenen Haut und dem silbrig weißem bis hellblonden Haaren. Dies kommt aber nicht durch das lichtscheue hausen in der Unterwellt, sondern stammt von ihrer Abstammung. Entstanden sind die Schattenelfen als sich Xe in einen jungen Waldelfen verliebte. Heraus kam die Halbgöttin Schar`xal, die Ahnherrin der Schattenelfen. Ihr Aussehen ist atemberaubend schön, aber die Färbung ihrer Haut und Haare ist genau entgegengesetzt, wie es bei einer normalen Hexe wäre.
	Ganz anders, als Oberflächenelfen, die sich nie für die Metallbearbeitung interessiert haben, tragen Schattenelfen liebend gerne metallische Rüstungen und Waffen. Diese stellen sie meistens aus Eisenerz her und verzieren diese prunkvoll mit Gold. Etwas ganz besonders sind Rüstungen aus Dunkelerz. Dunkelerz hat ähnliche Eigenschaften wie Mondsilber, aber unter Sonnenschein nehmen diese Schaden und zerfallen nach einiger Zeit. Aufgrund ihrer Abstammung glauben Schattenelfen göttliches Blut in ihren Adern, weswegen sie sich als die Herrscherrasse ansehen.
	Ihr Staat steht im völligen Zeichen dieser Ansicht. Schar`xal ist die Oberste Monarchin des Schattenelfenreichs, darunter Folgen die drei Adelshäuser, Do´Pak, Qe´Schan und Qual´Kuzz, darunter wiederum die normalen Dunkelelfen und zuletzt die Zahlreichen Sklaven, welche die Schattenelfen von Raubzügen an der Oberfläche und der Unterwelt mitbringen. Der zentrale Aspekt im Leben eines Schattenelfen ist, das Wohlwollen von Schar`xal. Um ihre Gunst streiten die unterschiedlichen Adelsgeschlechter miteinander und untereinander. So sind unbedingter Gehorsam und Intrigenschmieden die beiden wichtigsten Eigenschaften, die ein erfolgreicher Schattenelf beherrschen sollte. Dabei schrecken die Schattenelfen auch nicht vor Mord zurück, wobei sie dies keinesfalls selber erledigen, sondern von einem bestellten Attentäter erledigen lassen und dies am besten noch einem Konkurrenten in die Schuhe zu schieben, auf das dieser in Ungnade fällt.
	Im Kampf treiben die Dunkelelfen als erstes Kriegssklaven, meistens Ork, Goblins und Menschen in die Schlacht, um dann mit ihrer Elitetruppe den Wolfsreitern und den Schwarzklingen, unterstützt durch die Hexer unter den Feinden entsetzten zu sähen.
	„Die Schlacht endet, und das Schlachten beginnt“
	Dementsprechend schlecht sind auch die Beziehungen zu anderen Völkern, bei denen Dunkelelfen meistens nur verachtet, aber vor allem gefürchtet werden. Lediglich einzelne Menschliche Gruppierungen arbeiten manchmal mit ihnen zusammen, wie die Chaosmagier und die Gefolgschaften Kers.
	</p>
</div>

<?php include '../../../../includes/footer.html'; ?>